### PR TITLE
Silla

### PR DESCRIPTION
**Pull request by MechaShadowV2**
Hey, i, trying to upload the silla files, its saying i cant upload a file

### CODE REVIEW

**Comment by valrossenOliver** [comment]
You have put an empty file into review for merge into patch-1. I assume if you were trying to push you forgot to commit the actual changes. Also, your file lacks a file descriptor (for example .txt, .png, .jpeg) meaning the file cannot be interpreted.

**Comment by LumberKing** [comment]
It looks like you have yet to accept the invitation I have sent you for being a collaborator. Once you accept it, you'll be able to make pushes yourself.

**Comment by Pourov** [comment]
Hello Hansol,

Where can I locate the invitation? Still somewhat new to Github. Plus the desktop version does not have all the bells and whistles.

Also Sagimine1 is my paradox forum user name.

**Comment by MechaShadowV2** [comment]
Oh ok, thanks and sorry, I'll try again when I get home

Sent from Yahoo Mail on Android 
 
  On Fri, May 31, 2019 at 12:14 AM, Hamlet Millqvist<notifications@github.com> wrote:   
You have put an empty file into review for merge into patch-1. I assume if you were trying to push you forgot to commit the actual changes. Also, your file lacks a file descriptor (for example .txt, .png, .jpeg) meaning the file cannot be interpreted.

**Comment by LumberKing** [comment]
Pourov, it looks like you're already a collaborator. So, you're all good.

**Pull request closed without merging**
